# Generated by Django 5.2 on 2025-04-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_apoderado_alumno_descuento_mensualidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apoderado',
            name='usuario',
        ),
        migrations.AddField(
            model_name='apoderado',
            name='apellidom',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='apellidop',
            field=models.CharField(default='', max_length=100, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='email',
            field=models.EmailField(default='temporal@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='diasemana',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
