# Generated by Django 5.2 on 2025-04-16 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_apoderado_usuario_apoderado_apellidom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='cantidad_alumnos',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Alumnos'),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='descuentos_aplicados',
            field=models.CharField(default='Ninguno', max_length=500, verbose_name='Descuentos Aplicados'),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Inicial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='apellidom',
            field=models.CharField(max_length=100, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='apellidop',
            field=models.CharField(max_length=100, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='apoderado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Final'),
        ),
    ]
