# Generated by Django 5.2 on 2025-04-17 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_apoderado_cantidad_alumnos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnioEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(unique=True, verbose_name='Año Escolar')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Año Escolar',
                'verbose_name_plural': 'Años Escolares',
            },
        ),
        migrations.AddField(
            model_name='apoderado',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Mensualidades'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='anio_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='myapp.anioescolar'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='anio_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apoderados', to='myapp.anioescolar'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='anio_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='myapp.anioescolar'),
        ),
        migrations.AddField(
            model_name='curso',
            name='anio_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='myapp.anioescolar'),
        ),
        migrations.AddField(
            model_name='descuento',
            name='anio_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='myapp.anioescolar'),
        ),
        migrations.AddField(
            model_name='mensualidad',
            name='anio_escolar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='myapp.anioescolar'),
        ),
    ]
