# Generated by Django 5.2 on 2025-04-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_anioescolar_apoderado_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangoNoDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Rango')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos_no_disponibles', to='myapp.diasemana')),
            ],
            options={
                'verbose_name': 'Rango No Disponible',
                'verbose_name_plural': 'Rangos No Disponibles',
            },
        ),
    ]
