# Generated by Django 5.2 on 2025-04-21 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rangonodisponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.PositiveIntegerField(help_text='Límite de horas diarias en minutos (por ejemplo, 240 para 4 horas)', verbose_name='Horas (en minutos)')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_profesores', to='myapp.diasemana')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='myapp.profesor')),
            ],
            options={
                'verbose_name': 'Horario de Profesor',
                'verbose_name_plural': 'Horarios de Profesores',
                'unique_together': {('profesor', 'dia')},
            },
        ),
    ]
