# Generated by Django 5.2 on 2025-04-23 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_profesorhorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='apoderado',
            name='modalidad_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('letra', 'Letra')], default=django.utils.timezone.now, max_length=20, verbose_name='Modalidad de Pago'),
            preserve_default=False,
        ),
    ]
