# Generated by Django 5.2 on 2025-04-23 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_apoderado_modalidad_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='apellido',
            new_name='apellidom',
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellidop',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumno',
            name='anio_escolar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.anioescolar'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.curso'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
